name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 
  Build:
    runs-on: ubuntu-latest
    environment: AZ_ACR
    steps:
    - uses: actions/checkout@v3
    - name: Azure Container Registry Login 
      uses: azure/docker-login@v1 
      with:
        # Container registry server url
        login-server: ${{ secrets.LOGIN_SERVER }}
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }} 
    
    - name: Build and Push the Docker image
      run:  | 
       docker build . -t demoaksregistry01.azurecr.io/app1-nginx:v1.0.0
       docker push demoaksregistry01.azurecr.io/app1-nginx:v1.0.0

  AKS:
    name: Deploy AKS
    needs: [Build]
    runs-on: ubuntu-latest
    environment: aks-deployment
    steps:
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}

    - name: Get credentials
      env:
        CLUSTER_RESOURCE_GROUP_NAME: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      run: |
        az aks get-credentials \
          --resource-group $CLUSTER_RESOURCE_GROUP_NAME \
          --name $CLUSTER_NAME \
          --overwrite-existing


    # - name: dep
    #   env:
    #     SERVICE_PRINCIPLE_ID: ${{ secrets.SERVICE_PRINCIPLE_ID }}
    #     SERVICE_PRINCIPLE_PASSWORD: ${{ secrets.SERVICE_PRINCIPLE_PASSWORD }}
    #   run: |
