name: SampleWebApp CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: deployment-approval
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login 
      uses: azure/docker-login@v1 
      with:
        # Container registry server url
        login-server: demoaksregistry01.azurecr.io
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }} 
    
    - name: Build and Push the Docker image
      run:  | 
       docker build . -t demoaksregistry01.azurecr.io/app1-nginx:2.0.0
       docker push demoaksregistry01.azurecr.io/app1-nginx:2.0.0
